export const themeColors = {
  dark: {
    background: '#09090b',
    card: '#18181b',
    text: '#ffffff',
    textMuted: '#a1a1aa',
    border: 'rgba(255, 255, 255, 0.08)',
    borderMuted: 'rgba(255, 255, 255, 0.04)',
    inputBg: '#09090b',
    inputBorder: '#27272a',
    headerBg: '#121214',
    accent: '#f59e0b',
    accentBg: 'rgba(245, 158, 11, 0.1)',
    cardMuted: '#1e1e24',
    textDark: '#121214',
  },
  light: {
    background: '#f4f4f5',
    card: '#ffffff',
    text: '#09090b',
    textMuted: '#71717a',
    border: 'rgba(9, 9, 11, 0.08)',
    borderMuted: 'rgba(9, 9, 11, 0.04)',
    inputBg: '#ffffff',
    inputBorder: '#e4e4e7',
    headerBg: '#ffffff',
    accent: '#d97706',
    accentBg: 'rgba(217, 119, 6, 0.08)',
    cardMuted: '#f4f4f5',
    textDark: '#ffffff',
  }
};

export type ThemeColorsType = typeof themeColors.dark;

export function getThemedStyles(colors: ThemeColorsType, isTablet: boolean): any {
  return {
    // Login Screen Styles
    loginContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    loginScrollContainer: {
      flexGrow: 1,
      justifyContent: 'center',
      padding: 24,
    },
    loginCard: {
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: 24,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.4,
      shadowRadius: 30,
      elevation: 10,
      width: isTablet ? 450 : '100%',
      alignSelf: 'center',
    },
    brandContainer: {
      alignItems: 'center',
      marginBottom: 28,
    },
    brandLogo: {
      width: 60,
      height: 60,
      borderRadius: 18,
      backgroundColor: colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    brandTitle: {
      fontSize: 26,
      fontWeight: '900',
      color: colors.text,
      letterSpacing: -0.5,
    },
    brandAccent: {
      color: colors.accent,
    },
    brandSub: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 4,
      fontWeight: '500',
    },
    inputGroup: {
      marginBottom: 18,
    },
    inputLabel: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.textMuted,
      marginBottom: 8,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBg,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 14,
      paddingHorizontal: 14,
      height: 48,
    },
    inputIcon: {
      marginRight: 10,
    },
    input: {
      flex: 1,
      color: colors.text,
      fontSize: 14,
    },
    loginButton: {
      backgroundColor: colors.accent,
      borderRadius: 14,
      height: 50,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 12,
    },
    loginButtonText: {
      color: colors.textDark,
      fontSize: 15,
      fontWeight: 'bold',
    },
    demoFillBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBg,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 12,
      paddingHorizontal: 12,
      height: 40,
      marginTop: 8,
      gap: 10,
    },
    demoFillBtnText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: 'bold',
    },

    // Main App Shell Styles
    appContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 18,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.headerBg,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.5,
    },
    headerSubtitle: {
      fontSize: 11,
      color: colors.textMuted,
      marginTop: 2,
      fontWeight: '500',
    },
    refreshButton: {
      width: 38,
      height: 38,
      borderRadius: 12,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.inputBorder,
    },
    content: {
      flex: 1,
    },
    scrollContent: {
      padding: 20,
      paddingBottom: 40,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.background,
    },

    // Dashboard Tab Styles
    welcomeBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 20,
    },
    welcomeSubtitle: {
      fontSize: 12,
      color: colors.textMuted,
      fontWeight: '500',
    },
    welcomeTitle: {
      fontSize: 22,
      fontWeight: '800',
      color: colors.text,
      marginTop: 2,
      letterSpacing: -0.5,
    },
    welcomeRoleBadge: {
      backgroundColor: colors.accentBg,
      borderWidth: 1,
      borderColor: colors.accent,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 12,
    },
    welcomeRoleText: {
      color: colors.accent,
      fontSize: 10,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    commandGridRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 14,
    },
    commandGridItem: {
      width: '48.5%',
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 16,
      padding: 14,
      flexDirection: 'row',
      alignItems: 'center',
    },
    commandIconBox: {
      width: 38,
      height: 38,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    commandLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.text,
    },
    kpiGrid: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 20,
    },
    kpiCard: {
      flex: 1,
      borderRadius: 16,
      padding: 14,
      borderWidth: 1,
      backgroundColor: colors.card,
    },
    kpiLabel: {
      fontSize: 9,
      fontWeight: '800',
      color: colors.textMuted,
      textTransform: 'uppercase',
      marginBottom: 6,
      letterSpacing: 0.3,
    },
    kpiValue: {
      fontSize: 14,
      fontWeight: '900',
      color: colors.text,
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 14,
      marginTop: 10,
    },
    sectionHeader: {
      marginBottom: 14,
      marginTop: 10,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.3,
    },

    // Premium Cards Styles
    premiumCard: {
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 20,
    },
    premiumCardItem: {
      backgroundColor: colors.card,
      borderRadius: 18,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    projectScheduleCard: {
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cardHeaderTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.text,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
    },
    projectNameText: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
    },
    projectCodeLabel: {
      fontSize: 11,
      color: colors.accent,
      fontWeight: 'bold',
      marginTop: 2,
    },
    projectProgressPill: {
      backgroundColor: colors.accentBg,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
    },
    projectProgressText: {
      color: colors.accent,
      fontSize: 10,
      fontWeight: 'bold',
    },
    progressRailBg: {
      height: 6,
      backgroundColor: colors.background,
      borderRadius: 10,
      marginTop: 14,
      overflow: 'hidden',
    },
    progressRailFill: {
      height: '100%',
      backgroundColor: colors.accent,
      borderRadius: 10,
    },

    // Timeline & Audit Trails
    timelineWrapper: {
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.border,
    },
    timelineRow: {
      flexDirection: 'row',
      marginBottom: 16,
    },
    timelineLeftCol: {
      alignItems: 'center',
      marginRight: 12,
      width: 16,
    },
    timelineDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.accent,
      marginTop: 6,
    },
    timelineConnectorLine: {
      width: 1,
      backgroundColor: colors.border,
      position: 'absolute',
      top: 14,
      bottom: 0,
    },
    timelineContent: {
      flex: 1,
    },
    timelineDescText: {
      fontSize: 12,
      color: colors.text,
      lineHeight: 16,
    },
    timelineUser: {
      fontWeight: '700',
      color: colors.text,
    },
    timelineTimeText: {
      fontSize: 10,
      color: colors.textMuted,
      marginTop: 2,
    },
    emptyPlaceholderText: {
      textAlign: 'center',
      fontSize: 12,
      color: colors.textMuted,
      paddingVertical: 30,
      fontWeight: '500',
    },

    // Project Lists
    cardMetaLabel: {
      color: colors.textMuted,
      fontSize: 12,
      marginBottom: 4,
    },
    cardMetaValue: {
      color: colors.text,
      fontWeight: '500',
    },
    cardHighlightEstimate: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.accent,
    },

    // Project Details View
    detailHeaderBar: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.headerBg,
    },
    backButtonTrigger: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    detailHeaderTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
    },
    detailHeaderSubtitle: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: 'bold',
      marginTop: 2,
    },
    detailEditButton: {
      padding: 6,
      borderRadius: 8,
      backgroundColor: colors.card,
    },
    detailTabSelectorRail: {
      flexDirection: 'row',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.headerBg,
      paddingHorizontal: 12,
    },
    detailTabHeaderItem: {
      flex: 1,
      paddingVertical: 12,
      alignItems: 'center',
      borderBottomWidth: 2,
      borderBottomColor: 'transparent',
    },
    detailTabHeaderText: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.textMuted,
    },

    // Project Info Subtab
    infoFieldLabel: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.textMuted,
      textTransform: 'uppercase',
      marginTop: 12,
      marginBottom: 4,
      letterSpacing: 0.3,
    },
    infoFieldValue: {
      fontSize: 14,
      color: colors.text,
      lineHeight: 20,
    },
    infoDoubleGridRow: {
      flexDirection: 'row',
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 14,
      marginTop: 14,
    },

    // Tasks List inside Project detail
    taskTitleText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
      flex: 1,
    },
    taskDescText: {
      color: colors.textMuted,
      fontSize: 12,
      marginTop: 6,
      lineHeight: 18,
    },
    taskRowFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.borderMuted,
      paddingTop: 8,
    },
    taskAssigneeText: {
      color: colors.textMuted,
      fontSize: 11,
    },

    // Daily reports list inside project details
    logDateText: {
      fontSize: 13,
      fontWeight: 'bold',
      color: colors.accent,
    },
    logWeatherText: {
      color: colors.textMuted,
      fontSize: 12,
    },
    logWorkSummaryText: {
      color: colors.text,
      fontSize: 13,
      marginTop: 6,
      lineHeight: 18,
    },
    issuesBadgeContainer: {
      marginTop: 10,
      backgroundColor: 'rgba(244,63,94,0.06)',
      padding: 8,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: 'rgba(244,63,94,0.15)',
    },
    issuesBadgeText: {
      color: '#f43f5e',
      fontSize: 11,
      fontWeight: '500',
    },
    logRowFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 10,
      borderTopWidth: 1,
      borderTopColor: colors.borderMuted,
      paddingTop: 8,
    },
    logMetaDetails: {
      color: colors.textMuted,
      fontSize: 11,
    },

    // Tasks Screen filters & column tab selectors
    filterBarContainer: {
      padding: 16,
      backgroundColor: colors.headerBg,
      borderBottomWidth: 1,
      borderColor: colors.border,
    },
    horizontalKanbanSelectorContainer: {
      backgroundColor: colors.background,
      borderBottomWidth: 1,
      borderColor: colors.border,
      paddingVertical: 10,
    },
    kanbanColumnHeaderItem: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: colors.card,
      marginRight: 8,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    kanbanColumnHeaderText: {
      color: colors.textMuted,
      fontWeight: '700',
      fontSize: 11,
      textTransform: 'uppercase',
    },
    kanbanCountBubble: {
      marginLeft: 6,
      backgroundColor: colors.inputBorder,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 10,
    },
    kanbanCountBubbleText: {
      color: colors.textMuted,
      fontSize: 9,
      fontWeight: 'bold',
    },
    taskDueDateLabel: {
      color: colors.textMuted,
      fontSize: 11,
      marginTop: 8,
    },
    taskCardActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 8,
      marginTop: 10,
    },

    // Finance Tab overview stats card
    premiumFinanceOverviewCard: {
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 20,
    },
    premiumEarningsEstimate: {
      fontSize: 14,
      fontWeight: '800',
      color: '#10b981',
    },

    // Materials & Suppliers
    miniActionApproveBtn: {
      backgroundColor: 'rgba(16,185,129,0.1)',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
    },
    miniActionDeliverBtn: {
      backgroundColor: 'rgba(96,165,250,0.1)',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
    },
    stockAlertLabelContainer: {
      backgroundColor: colors.accentBg,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
    },
    stockAlertLabelText: {
      color: colors.accent,
      fontSize: 8,
      fontWeight: 'bold',
    },
    capsuleBadge: {
      backgroundColor: colors.inputBorder,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
    },
    capsuleBadgeText: {
      color: colors.text,
      fontSize: 9,
      fontWeight: '500',
    },

    // Workers & Attendance Layout
    attendanceStatusBtn: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: 'transparent',
    },
    attendanceStatusBtnText: {
      color: colors.textMuted,
      fontSize: 9,
      fontWeight: 'bold',
    },

    // Profile Settings card
    profileSection: {
      alignItems: 'center',
      paddingVertical: 24,
      backgroundColor: colors.card,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 20,
    },
    avatarLarge: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: colors.accentBg,
      borderWidth: 2,
      borderColor: colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    avatarLargeText: {
      fontSize: 24,
      fontWeight: 'bold',
      color: colors.accent,
    },
    profileName: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.text,
    },
    profileRole: {
      fontSize: 11,
      color: colors.accent,
      fontWeight: 'bold',
      marginTop: 4,
      textTransform: 'uppercase',
    },
    profileEmail: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 4,
    },

    // Menu/More sub-grid
    menuModulesGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 20,
    },
    menuGridItem: {
      width: isTablet ? '31.5%' : '48%',
      backgroundColor: colors.card,
      padding: 16,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
    },
    menuItemIconBox: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    menuItemLabel: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    menuItemDesc: {
      color: colors.textMuted,
      fontSize: 10,
      marginTop: 2,
      textAlign: 'center',
    },

    // Buttons configurations
    premiumHeaderButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.accent,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 8,
    },
    premiumHeaderBtnText: {
      fontSize: 11,
      fontWeight: 'bold',
      color: colors.textDark,
      marginLeft: 2,
    },
    premiumActionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      height: 42,
      borderRadius: 12,
      flex: 1,
    },
    premiumActionText: {
      fontSize: 13,
      fontWeight: 'bold',
      marginLeft: 4,
    },
    logoutButton: {
      backgroundColor: 'rgba(244, 63, 94, 0.08)',
      borderWidth: 1,
      borderColor: 'rgba(244, 63, 94, 0.2)',
      borderRadius: 14,
      height: 46,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 10,
    },
    logoutButtonText: {
      color: '#f43f5e',
      fontSize: 13,
      fontWeight: 'bold',
    },

    // Modal styling
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(9, 9, 11, 0.8)',
      justifyContent: 'center',
      padding: 20,
    },
    modalContentCard: {
      backgroundColor: colors.card,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      maxHeight: '85%',
      overflow: 'hidden',
      width: isTablet ? 540 : '100%',
      alignSelf: 'center',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 18,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.text,
    },
    modalFormBody: {
      padding: 18,
    },
    formLabel: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.textMuted,
      marginBottom: 6,
      marginTop: 12,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    modalInput: {
      backgroundColor: colors.inputBg,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 12,
      color: colors.text,
      paddingHorizontal: 12,
      height: 42,
      fontSize: 13,
      marginBottom: 6,
    },
    textArea: {
      height: 70,
      paddingTop: 8,
      textAlignVertical: 'top',
    },
    formRow: {
      flexDirection: 'row',
    },
    modalFooter: {
      flexDirection: 'row',
      padding: 18,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      gap: 10,
    },
    modalCancelBtn: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cancelBtnText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
    },
    modalSubmitBtn: {
      flex: 1,
      backgroundColor: colors.accent,
      borderRadius: 12,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    submitBtnText: {
      color: colors.textDark,
      fontSize: 13,
      fontWeight: 'bold',
    },

    // Dropdown selector custom popup modal
    dropdownTrigger: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBg,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 12,
      paddingHorizontal: 12,
      height: 42,
    },
    dropdownTriggerText: {
      fontSize: 13,
      flex: 1,
    },
    dropdownModalContent: {
      backgroundColor: colors.card,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      maxHeight: '60%',
      overflow: 'hidden',
      width: isTablet ? 540 : '100%',
      alignSelf: 'center',
    },
    dropdownModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    dropdownModalTitle: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.text,
    },
    dropdownItem: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderMuted,
      borderRadius: 8,
      marginBottom: 4,
    },
    dropdownItemActive: {
      backgroundColor: colors.accentBg,
    },
    dropdownItemText: {
      color: colors.text,
      fontSize: 13,
    },
    dropdownItemTextActive: {
      color: colors.accent,
      fontWeight: '700',
    },

    // Allocation splits Purchase modal
    allocationSplitSection: {
      marginTop: 16,
      borderTopWidth: 1,
      borderTopColor: colors.borderMuted,
      paddingTop: 14,
    },
    allocationSectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    allocTitle: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
    },
    allocAddRowBtn: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    allocAddRowText: {
      fontSize: 10,
      color: colors.accent,
      fontWeight: 'bold',
      marginLeft: 2,
    },
    allocationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
      gap: 4,
    },
    allocDeleteBtn: {
      width: 32,
      height: 38,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statusSwitchRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 14,
      paddingVertical: 4,
    },
    statusSwitchLabel: {
      fontSize: 12,
      color: colors.text,
    },

    tabletGridContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    tabletGridCard: {
      width: '49%',
      marginBottom: 12,
    },

    // Member card configs
    memberCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 14,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    memberInfoCol: {
      flex: 1,
    },
    memberName: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    memberEmail: {
      fontSize: 11,
      color: colors.textMuted,
      marginTop: 2,
    },
    badgeRow: {
      flexDirection: 'row',
      gap: 6,
      marginTop: 8,
    },
    memberRoleBadge: {
      backgroundColor: colors.inputBorder,
      paddingHorizontal: 6,
      paddingVertical: 3,
      borderRadius: 6,
    },
    roleBadgeText: {
      fontSize: 8,
      fontWeight: '800',
      color: colors.text,
      textTransform: 'uppercase',
    },
    statusBadge: {
      paddingHorizontal: 6,
      paddingVertical: 3,
      borderRadius: 6,
    },
    bgActive: {
      backgroundColor: 'rgba(16, 185, 129, 0.1)',
    },
    bgInactive: {
      backgroundColor: 'rgba(161, 161, 170, 0.1)',
    },
    statusBadgeText: {
      fontSize: 8,
      fontWeight: '800',
      color: '#ffffff',
    },
    memberActionsRow: {
      flexDirection: 'row',
      gap: 6,
    },
    actionIconButton: {
      width: 30,
      height: 30,
      borderRadius: 8,
      backgroundColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconButtonContainer: {
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: colors.inputBorder,
      justifyContent: 'center',
      alignItems: 'center',
    },

    // Bottom nav bar configurations
    tabBar: {
      flexDirection: 'row',
      height: 60,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.headerBg,
      justifyContent: 'space-around',
      alignItems: 'center',
    },
    tabItem: {
      alignItems: 'center',
      justifyContent: 'center',
      flex: 1,
      height: '100%',
    },
    tabText: {
      fontSize: 9,
      color: colors.textMuted,
      marginTop: 4,
      fontWeight: '600',
    },
    // Wallet header card
    walletHeaderCard: {
      borderRadius: 20,
      padding: 20,
      borderWidth: 1,
      marginBottom: 20,
    },
    walletLabel: {
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 4,
    },
    walletBalance: {
      fontSize: 28,
      fontWeight: '900',
      letterSpacing: -0.5,
    },
    walletSummaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 16,
      borderTopWidth: 1,
      paddingTop: 16,
    },
    walletStatLabel: {
      fontSize: 9,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.3,
      marginBottom: 4,
    },
    walletStatValue: {
      fontSize: 15,
      fontWeight: '900',
    },
    breakdownValuesRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 10,
    },
    breakdownColumn: {
      flex: 1,
    },
    breakdownLabel: {
      fontSize: 9,
      fontWeight: '800',
      textTransform: 'uppercase',
      marginBottom: 4,
    },
    breakdownVal: {
      fontWeight: 'bold',
    },
    financeHeaderButtons: {
      flexDirection: 'row',
      gap: 10,
      padding: 16,
      borderBottomWidth: 1,
    },
    financeActionBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      flex: 1,
      height: 40,
      borderRadius: 12,
    },
    financeBtnText: {
      fontSize: 12,
      fontWeight: 'bold',
      marginLeft: 4,
    },
    btnIcon: {
      marginRight: 2,
    },
    subTabsContainer: {
      flexDirection: 'row',
      borderBottomWidth: 1,
      paddingHorizontal: 16,
    },
    subTabItem: {
      paddingVertical: 12,
      marginRight: 16,
      borderBottomWidth: 2,
      borderBottomColor: 'transparent',
    },
    subTabText: {
      fontSize: 12,
      fontWeight: '600',
    },
    purchaseAllocationList: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: 10,
    },
    allocationPill: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      borderWidth: 1,
    },
    allocationPillText: {
      fontSize: 10,
      fontWeight: '500',
    },
  };
}
